% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Aug-2025 07:44:44
%  MATLAB version: 24.2.0.2773142 (R2024b) Update 2
% -------------------------------------------------------------------
                                                    

Param = Simulink.Parameter;
Param.Value = [];
Param.Complexity = 'real';
Param.HasCoderInfo = false;
Param.Description = '';
Param.DataType = 'auto';
Param.Min = [];
Param.Max = [];
Param.DocUnits = '';

sample_period_ms = 100;

